name: d2g
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.19
  - numpy=1.26.4
  - scipy=1.13.1
  - pyyaml=6.0.2
  - svgwrite=1.4.3
  - psutil=6.0.0
  - matplotlib
  - svgpathtools
  - cairosvg=2.7.1
  - nicegui=2.15.0
  - trimesh
  - cgal
  - pip
